plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
remote_theme: sharu725/online-cv
github: [metadata]

# Name of website
title: spriteCloud Resume

# Your name to show in the footer
author: spriteCloud

# Site Settings
# url: 'http://example.com'

#change it according to your repository name
# disabling since we are using a custom domain
#baseurl: '/online-cv'

description: Finest QA Engineers in the market.
# Style will be applied only after restarting the build or serve. Just choose one of the options.
theme_skin: blue # blue turquoise green berry orange ceramic
chrome_mobile_color: #use hex colors (ex:#1976d2) or leave empty if you don't want a color for chrome mobile searchbar